name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g postcss-cli autoprefixer
          npm install -g tailwindcss

      - name: Build CSS
        run: |
          cd website
          tailwindcss -i ./css/styles.css -o ./css/styles.min.css --minify
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website # The folder containing your website
          branch: gh-pages # The branch the action should deploy to
